# Generated by Django 6.0.4 on 2026-04-14 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compartimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Número de Compartimiento')),
                ('is_empty', models.BooleanField(default=True, verbose_name='Está vacío')),
                ('medicina', models.CharField(blank=True, max_length=100, verbose_name='Medicina contenida')),
            ],
            options={
                'verbose_name': 'Compartimiento',
                'verbose_name_plural': 'Compartimientos',
                'ordering': ['robot', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_dispensado', models.TimeField(verbose_name='Hora de dispensado')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('DISPENSED', 'Dispensado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('compartimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='core.compartimiento')),
            ],
            options={
                'verbose_name': 'Programación',
                'verbose_name_plural': 'Programaciones',
                'ordering': ['hora_dispensado'],
            },
        ),
        migrations.CreateModel(
            name='RegistroMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('mensaje_confirmacion', models.TextField(blank=True, verbose_name='Mensaje de Confirmación (Raw)')),
                ('exitosa', models.BooleanField(default=True, verbose_name='Toma Exitosa')),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='core.programacion')),
            ],
            options={
                'verbose_name': 'Registro Médico',
                'verbose_name_plural': 'Registros Médicos',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(help_text='Ejemplo: 00:1B:44:11:3A:B7', max_length=17, unique=True, verbose_name='MAC Address')),
                ('is_connected', models.BooleanField(default=False, verbose_name='Conectado')),
                ('patient', models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'PATIENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robots', to=settings.AUTH_USER_MODEL, verbose_name='Paciente Asignado')),
            ],
            options={
                'verbose_name': 'Robot',
                'verbose_name_plural': 'Robots',
            },
        ),
        migrations.AddField(
            model_name='compartimiento',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartimientos', to='core.robot'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('PATIENT', 'Paciente'), ('CAREGIVER', 'Cuidador')], default='PATIENT', max_length=20, verbose_name='Rol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.AlterUniqueTogether(
            name='compartimiento',
            unique_together={('robot', 'numero')},
        ),
    ]
